IF(CMAKE_VERSION VERSION_LESS "3.10.0")
    IF(DEFINED BEYOND_ANDROID_GSTREAMER)
        RETURN()
    ENDIF()
    SET(BEYOND_ANDROID_GSTREAMER TRUE)
ELSE(CMAKE_VERSION VERSION_LESS "3.10.0")
    INCLUDE_GUARD(GLOBAL)
ENDIF(CMAKE_VERSION VERSION_LESS "3.10.0")

IF(ANDROID_ABI STREQUAL "arm64-v8a")
    SET(GSTREAMER_ABI arm64)
ELSEIF(ANDROID_ABI STREQUAL "armeabi-v7a")
    SET(GSTREAMER_ABI armv7)
ELSE(ANDROID_ABI STREQUAL "armeabi-v7a")
    SET(GSTREAMER_ABI ${ANDROID_ABI})
ENDIF(ANDROID_ABI STREQUAL "arm64-v8a")

INCLUDE_DIRECTORIES(
    ${GSTREAMER_ROOT_ANDROID}/${GSTREAMER_ABI}/include/gstreamer-1.0
    ${GSTREAMER_ROOT_ANDROID}/${GSTREAMER_ABI}/include/glib-2.0
    ${GSTREAMER_ROOT_ANDROID}/${GSTREAMER_ABI}/lib/glib-2.0/include
)

LINK_DIRECTORIES(${GSTREAMER_ROOT_ANDROID}/${GSTREAMER_ABI}/lib)

SET(GST_LIBRARIES -lgio-2.0 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -liconv -lintl -lffi)
